cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o list.o list.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstrlib.o bstrlib.c  && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o list.o    list_tests.c   -o list_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o list_algos.o list_algos.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstrlib.o bstrlib.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o list.o list_algos.o    list_algos_tests.c   -o list_algos_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o darray.o darray.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  darray.o    darray_tests.c   -o darray_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o darray_algos.o darray_algos.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG darray.o  darray_algos.o    darray_algos_tests.c   -o darray_algos_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o radixmap.o radixmap.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  radixmap.o    radixmap_tests.c   -o radixmap_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o hashmap.o hashmap.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstrlib.o bstrlib.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o darray.o darray_algos.o hashmap.o    hashmap_tests.c   -o hashmap_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o hashmap_algos.o hashmap_algos.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstrlib.o bstrlib.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o darray.o darray_algos.o hashmap.o hashmap_algos.o    hashmap_algos_tests.c   -o hashmap_algos_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o string_algos.o string_algos.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstrlib.o bstrlib.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o darray.o string_algos.o    string_algos_tests.c   -o string_algos_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstree.o bstree.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstrlib.o bstrlib.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o bstree.o    bstree_tests.c   -o bstree_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstree_iter.o bstree_iter.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstrlib.o bstrlib.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o bstree_iter.o    bstree_iter_tests.c   -o bstree_iter_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstree_hash.o bstree_hash.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstrlib.o bstrlib.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o bstree_hash.o    bstree_hash_tests.c   -o bstree_hash_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG bstrlib.o list.o  stack_tests.c   -o stack_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG bstrlib.o list.o  queue_tests.c   -o queue_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG darray.o stack_darray_tests.c   -o stack_darray_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG -fPIC   -c -o stats.o stats.c &&  cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG stats.o    stats_tests.c   -o stats_tests -lm
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o darray.o string_algos.o stats.o    string_algos_stats_tests.c   -o string_algos_stats_tests -lm
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o ringbuffer.o ringbuffer.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o bstrlib.o bstrlib.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o ringbuffer.o    ringbuffer_tests.c   -o ringbuffer_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o ringbuffer_posix.o ringbuffer_posix.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  ringbuffer_posix.o    ringbuffer_posix_tests.c   -o ringbuffer_posix_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o netclient.o netclient.c && cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  ringbuffer.o bstrlib.o netclient.o -o netclient
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o tstree.o tstree.c &&  cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o darray.o tstree.o    tstree_tests.c   -o tstree_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  -fPIC   -c -o tstree_mod.o tstree_mod.c &&  cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG  bstrlib.o darray.o tstree_mod.o    tstree_mod_tests.c   -o tstree_mod_tests
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG tstree.o bstrlib.o urlrouter.c   -o urlrouter
cc -g -O2 -Wall -Wextra -Isrc -rdynamic -DNDEBUG tstree.o bstrlib.o urlrouter_mod.c   -o urlrouter_mod
